apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pvu7mul42-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-5b7314a0db.0jv5.p3.openshiftapps.com/rhtap/rhtap-qe:b470de82b06747a0998d47010baad39a4480c9fb@sha256:dfe587645e1e5c7e78991d7fc5c318943f917258c5c7d3f6507c0ed9cec8d038
          name: container-image
